[package]
name = "slab-allocator"
version = "0.1.0"
edition = "2021"

[lib]
name = "slab_allocator"
path = "src/lib.rs"

[dependencies]
spin = "0.9.8"

[dev-dependencies]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
opt-level = 3
